dist: xenial

os: linux

language: python

python:
  - 3.9

services:
  - docker

script:
  - pip install -r requirements.txt
  - python -m unittest discover test

deploy:
  provider: script
  script: bash travis/docker_build_push.sh
  on:
    branch: master
